version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Adjust the port if needed
    x-develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Adjust the port if needed
      - "5173:5173"  # dev

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_trading
    ports:
      - "5432:5432"  # Adjust the port if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
