version: "3.8"
services:
  frontend:
    image: frontend-prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: frontend-prod-c
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=5001
  backend:
    image: backend-prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: backend-prod-c
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_trading
    ports:
      - "5432:5432" # Adjust the port if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
